# fly.toml app configuration file generated for todo-api-hakan on 2023-12-18T07:59:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todo-api-hakan"
primary_region = "ams"

[build]

[http_service]
internal_port = 8080
force_https = true
# auto_stop_machines = true
# auto_start_machines = true
min_machines_running = 2
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
